// frontend/src/components/FinanceDashboard.jsx
import React, { useEffect, useState, useCallback, useRef } from "react";
import toast from "react-hot-toast";
import Navbar from "./Navbar.jsx";
import FilterBar from "./FilterBar.jsx";
import StatCards from "./StatCards.jsx";
import FinanceCharts from "./FinanceCharts.jsx";
import FinanceTable from "./FinanceTable.jsx";
import FinanceEntryForm from "./FinanceEntryForm.jsx";
import api from "../api/axios.js";

const firstOfMonth = () => {
  const d = new Date();
  return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().split("T")[0];
};
const todayStr = () => new Date().toISOString().split("T")[0];

export default function FinanceDashboard({
  department,
  title,
  roleColor,
  paginateByCategory = false,
  itemsPerPage = 30,
}) {
  const apiBase = department.toLowerCase().replace(/\s/g, '');
  const supportsExcelImportExport = department === "PCM";

  const [startDate, setStartDate] = useState(firstOfMonth());
  const [endDate, setEndDate] = useState(todayStr());
  const [searchTerm, setSearchTerm] = useState("");

  const [entries, setEntries] = useState([]);
  const [summary, setSummary] = useState(null);
  const [options, setOptions] = useState(null);
  const [loading, setLoading] = useState(true);
  const [importing, setImporting] = useState(false);

  const [selectedCategory, setSelectedCategory] = useState(null);
  const [currentPage, setCurrentPage] = useState(1);

  const [formOpen, setFormOpen] = useState(false);
  const [editingEntry, setEditingEntry] = useState(null);

  const fileInputRef = useRef(null);

  const fetchOptions = useCallback(async () => {
    try {
      const res = await api.get(`/${apiBase}/options`);
      setOptions(res.data);
    } catch {
      toast.error("Failed to load form options.");
    }
  }, [apiBase]);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const params = { start_date: startDate, end_date: endDate };
      if (searchTerm) params.search = searchTerm;

      const [entriesRes, summaryRes] = await Promise.all([
        api.get(`/${apiBase}/entries`, { params }),
        api.get(`/${apiBase}/summary`, { params: { start_date: startDate, end_date: endDate } }),
      ]);

      const entriesData = Array.isArray(entriesRes.data)
        ? entriesRes.data
        : (entriesRes.data.entries || []);

      setEntries(entriesData);
      setSummary(summaryRes.data);

      if (paginateByCategory) {
        setSelectedCategory(null);
        setCurrentPage(1);
      }
    } catch (err) {
      toast.error("Failed to load finance data.");
    } finally {
      setLoading(false);
    }
  }, [apiBase, startDate, endDate, searchTerm, paginateByCategory]);

  useEffect(() => {
    fetchOptions();
  }, [fetchOptions]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleReset = () => {
    setStartDate(firstOfMonth());
    setEndDate(todayStr());
    setSearchTerm("");
  };

  const handleDelete = async (entry) => {
    if (!window.confirm(`Delete this ${entry.entry_type.toLowerCase()} entry dated ${entry.entry_date}?`)) return;
    try {
      await api.delete(`/${apiBase}/entries/${entry.id}`);
      toast.success("Entry deleted.");
      fetchData();
    } catch {
      toast.error("Failed to delete entry.");
    }
  };

  const handleExportCsv = () => {
    if (!entries.length) {
      toast.error("No entries to export.");
      return;
    }
    const headers = ["Date", "Type", "Category", "Patient Name", "Patient Place", "Generated By", "Revenue Type", "Amount", "Remarks"];
    const rows = entries.map((e) => [
      e.entry_date, e.entry_type, e.category, e.patient_name || "", e.patient_place || "",
      e.generated_by || "", e.revenue_type || "", e.amount,
      (e.remarks || "").replace(/,/g, ";"),
    ]);
    const csv = [headers, ...rows].map((r) => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${department}_Finance_${startDate}_to_${endDate}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportExcel = async () => {
    try {
      const res = await api.get(`/${apiBase}/export`, {
        params: { start_date: startDate, end_date: endDate },
        responseType: "blob",
      });
      const blob = new Blob([res.data], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${department}_Finance_${startDate}_to_${endDate}.xlsx`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      toast.error("Failed to export Excel file.");
    }
  };

  const handleExport = () => {
    if (supportsExcelImportExport) {
      handleExportExcel();
    } else {
      handleExportCsv();
    }
  };

  const handleImportClick = () => {
    fileInputRef.current?.click();
  };

  const handleImportFileChange = async (e) => {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;

    const formData = new FormData();
    formData.append("file", file);

    setImporting(true);
    try {
      const res = await api.post(`/${apiBase}/import`, formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      const { imported, errors } = res.data;
      if (imported > 0) {
        toast.success(`Imported ${imported} entr${imported === 1 ? "y" : "ies"}.`);
      }
      if (errors && errors.length) {
        toast.error(`${errors.length} row(s) skipped — check the sheet formatting.`);
      }
      fetchData();
    } catch (err) {
      const msg = err.response?.data?.message || "Failed to import the Excel file.";
      toast.error(msg);
    } finally {
      setImporting(false);
    }
  };

  const categoriesWithCounts = React.useMemo(() => {
    if (!paginateByCategory) return [];
    const counts = {};
    entries.forEach(e => {
      counts[e.category] = (counts[e.category] || 0) + 1;
    });
    return Object.entries(counts)
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([category, count]) => ({ category, count }));
  }, [entries, paginateByCategory]);

  const filteredEntries = React.useMemo(() => {
    if (!paginateByCategory || !selectedCategory) return entries;
    return entries.filter(e => e.category === selectedCategory);
  }, [entries, paginateByCategory, selectedCategory]);

  const totalItems = filteredEntries.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage) || 1;
  const paginatedEntries = React.useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    return filteredEntries.slice(start, start + itemsPerPage);
  }, [filteredEntries, currentPage, itemsPerPage]);

  const handlePageChange = (page) => {
    if (page < 1 || page > totalPages) return;
    setCurrentPage(page);
  };

  useEffect(() => {
    setCurrentPage(1);
  }, [selectedCategory]);

  const openNewEntry = () => {
    setEditingEntry(null);
    setFormOpen(true);
  };

  const openEditEntry = (entry) => {
    setEditingEntry(entry);
    setFormOpen(true);
  };

  return (
    <div className="page">
      <Navbar title={title} roleColor={roleColor} />

      <main className="page-main">
        <FilterBar
          startDate={startDate}
          endDate={endDate}
          onStartDateChange={setStartDate}
          onEndDateChange={setEndDate}
          onApply={fetchData}
          onReset={handleReset}
          onExport={handleExport}
          onAddNew={openNewEntry}
          searchTerm={searchTerm}
          onSearchChange={setSearchTerm}
        />

        {supportsExcelImportExport && (
          <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 12 }}>
            <input
              ref={fileInputRef}
              type="file"
              accept=".xlsx,.xlsm"
              style={{ display: "none" }}
              onChange={handleImportFileChange}
            />
            <button
              type="button"
              className="btn btn-secondary"
              onClick={handleImportClick}
              disabled={importing}
            >
              {importing ? "Importing..." : "Import Excel"}
            </button>
          </div>
        )}

        {summary && (
          <StatCards
            totalIncome={summary.total_income}
            totalExpenses={summary.total_expenses}
            profit={summary.profit}
            entryCount={summary.entry_count}
          />
        )}

        {summary && (
          <FinanceCharts trend={summary.trend} categoryBreakdown={summary.category_breakdown} />
        )}

        {paginateByCategory && (
          <div className="category-selector" style={{ marginBottom: 20 }}>
            <h3 style={{ marginBottom: 8 }}>Select a Category</h3>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
              {categoriesWithCounts.map(({ category, count }) => (
                <button
                  key={category}
                  className={`btn ${selectedCategory === category ? "btn-primary" : "btn-secondary"}`}
                  onClick={() => setSelectedCategory(category)}
                  style={{ padding: "6px 14px" }}
                >
                  {category} ({count})
                </button>
              ))}
              {categoriesWithCounts.length === 0 && <span className="text-muted">No categories with data.</span>}
            </div>
          </div>
        )}

        <div>
          <p className="section-title" style={{ marginBottom: 12 }}>
            {paginateByCategory && selectedCategory
              ? `${selectedCategory} (${totalItems})`
              : "Finance Entries"}
          </p>

          {loading ? (
            <div className="card empty-state">Loading...</div>
          ) : (
            <>
              {(!paginateByCategory || selectedCategory) ? (
                <>
                  <FinanceTable
                    entries={paginatedEntries}
                    onEdit={openEditEntry}
                    onDelete={handleDelete}
                  />

                  {paginateByCategory && totalPages > 1 && (
                    <div className="pagination" style={{ marginTop: 16, display: "flex", justifyContent: "center", gap: 8, alignItems: "center" }}>
                      <button
                        className="btn btn-secondary"
                        onClick={() => handlePageChange(currentPage - 1)}
                        disabled={currentPage === 1}
                      >
                        Previous
                      </button>
                      <span>
                        Page {currentPage} of {totalPages}
                      </span>
                      {[...Array(totalPages).keys()].map(i => (
                        <button
                          key={i}
                          className={`btn ${currentPage === i + 1 ? "btn-primary" : "btn-secondary"}`}
                          onClick={() => handlePageChange(i + 1)}
                          style={{ padding: "4px 10px" }}
                        >
                          {i + 1}
                        </button>
                      ))}
                      <button
                        className="btn btn-secondary"
                        onClick={() => handlePageChange(currentPage + 1)}
                        disabled={currentPage === totalPages}
                      >
                        Next
                      </button>
                    </div>
                  )}
                </>
              ) : (
                <div className="card empty-state">
                  Please select a category to view its entries.
                </div>
              )}
            </>
          )}
        </div>
      </main>

      <FinanceEntryForm
        open={formOpen}
        onClose={() => setFormOpen(false)}
        onSaved={fetchData}
        department={department}
        options={options}
        editingEntry={editingEntry}
      />
    </div>
  );
}