import React, { useState, useEffect } from "react";
import { X } from "lucide-react";
import toast from "react-hot-toast";
import api from "../api/axios.js";

const today = () => new Date().toISOString().split("T")[0];

export default function FinanceEntryForm({ open, onClose, onSaved, department, options, editingEntry }) {
  const apiBase = department.toLowerCase();

  const emptyForm = () => ({
    entry_type: "Income",
    category: options?.categories?.Income?.[0] || "",
    generated_by: "",
    revenue_type: options?.revenue_types?.[0] || "",
    patient_name: "",
    patient_place: "",
    client_name: "",
    amount: "",
    remarks: "",
    entry_date: today(),
  });

  const [form, setForm] = useState(emptyForm());
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!open) return;
    if (editingEntry) {
      setForm({
        entry_type: editingEntry.entry_type,
        category: editingEntry.category,
        generated_by: editingEntry.generated_by || "",
        revenue_type: editingEntry.revenue_type || options?.revenue_types?.[0] || "",
        patient_name: editingEntry.patient_name || "",
        patient_place: editingEntry.patient_place || "",
        client_name: editingEntry.client_name || "",
        amount: editingEntry.amount,
        remarks: editingEntry.remarks || "",
        entry_date: editingEntry.entry_date,
      });
    } else {
      setForm(emptyForm());
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editingEntry, open, options]);

  if (!open || !options) return null;

  const categoryOptionsForType = options.categories[form.entry_type] || [];

  const handleTypeChange = (e) => {
    const newType = e.target.value;
    const firstCategory = options.categories[newType]?.[0] || "";
    setForm({ ...form, entry_type: newType, category: firstCategory });
  };

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (options.show_generated_by && !form.generated_by.trim()) {
      toast.error("Please enter the employee name (Generated By).");
      return;
    }
    if (options.show_patient_fields && !form.patient_name.trim()) {
      toast.error("Please enter the patient name.");
      return;
    }
    if (!form.amount || Number(form.amount) <= 0) {
      toast.error("Please enter a valid amount.");
      return;
    }

    const payload = { ...form };
    if (!options.show_generated_by) delete payload.generated_by;
    if (!options.show_revenue_type) delete payload.revenue_type;
    if (!options.show_patient_fields) {
      delete payload.patient_name;
      delete payload.patient_place;
    }
    if (!options.show_client_name) delete payload.client_name;

    setSaving(true);
    try {
      if (editingEntry) {
        await api.put(`/${apiBase}/entries/${editingEntry.id}`, payload);
        toast.success("Entry updated.");
      } else {
        await api.post(`/${apiBase}/entries`, payload);
        toast.success("Entry added.");
      }
      onSaved();
      onClose();
    } catch (err) {
      const msg = err.response?.data?.errors?.join(" ") || err.response?.data?.message || "Something went wrong.";
      toast.error(msg);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="modal-overlay">
      <div className="modal">
        <div className="modal-header">
          <h2>{editingEntry ? "Edit Finance Entry" : "New Finance Entry"}</h2>
          <button onClick={onClose} className="modal-close">
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="modal-body">
          <div className="form-group">
            <label className="form-label">Department</label>
            <input value={department} disabled className="form-control" />
          </div>

          <div className="form-row">
            <div className="form-group">
              <label className="form-label">Type</label>
              <select name="entry_type" value={form.entry_type} onChange={handleTypeChange} className="form-control">
                {options.entry_types.map((t) => <option key={t} value={t}>{t}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Category</label>
              <select name="category" value={form.category} onChange={handleChange} className="form-control">
                {categoryOptionsForType.map((c) => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
          </div>

          {options.show_client_name && (
            <div className="form-row">
              <div className="form-group">
                <label className="form-label">Client Name</label>
                <input
                  name="client_name"
                  value={form.client_name}
                  onChange={handleChange}
                  placeholder="Enter the client name"
                  className="form-control"
                />
              </div>
            </div>
          )}

          {options.show_patient_fields && (
            <div className="form-row">
              <div className="form-group">
                <label className="form-label">Patient Name</label>
                <input
                  name="patient_name"
                  value={form.patient_name}
                  onChange={handleChange}
                  placeholder="e.g. Ramesh Kumar"
                  className="form-control"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Patient Place</label>
                <input
                  name="patient_place"
                  value={form.patient_place}
                  onChange={handleChange}
                  placeholder="e.g. Guntur"
                  className="form-control"
                />
              </div>
            </div>
          )}

          {(options.show_generated_by || options.show_revenue_type) && (
            <div className="form-row">
              {options.show_generated_by && (
                <div className="form-group">
                  <label className="form-label">Generated By (Employee Name)</label>
                  <input
                    name="generated_by"
                    value={form.generated_by}
                    onChange={handleChange}
                    placeholder="e.g. John Mathew"
                    className="form-control"
                  />
                </div>
              )}
              {options.show_revenue_type && (
                <div className="form-group">
                  <label className="form-label">Revenue Type</label>
                  <select name="revenue_type" value={form.revenue_type} onChange={handleChange} className="form-control">
                    {options.revenue_types.map((r) => <option key={r} value={r}>{r}</option>)}
                  </select>
                </div>
              )}
            </div>
          )}

          <div className="form-row">
            <div className="form-group">
              <label className="form-label">Amount (₹)</label>
              <input
                type="number"
                step="0.01"
                min="0"
                name="amount"
                value={form.amount}
                onChange={handleChange}
                placeholder="0.00"
                className="form-control"
              />
            </div>
            <div className="form-group">
              <label className="form-label">Date</label>
              <input
                type="date"
                name="entry_date"
                value={form.entry_date}
                onChange={handleChange}
                className="form-control"
              />
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Remarks</label>
            <textarea
              name="remarks"
              value={form.remarks}
              onChange={handleChange}
              rows={3}
              placeholder="Optional notes about this entry"
              className="form-control"
            />
          </div>

          <div className="modal-footer">
            <button type="button" onClick={onClose} className="btn btn-secondary">Cancel</button>
            <button type="submit" disabled={saving} className="btn btn-primary">
              {saving ? "Saving..." : editingEntry ? "Update Entry" : "Save Entry"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}