import React from "react";
import { Pencil, Trash2 } from "lucide-react";

const formatCurrency = (value) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);

export default function FinanceTable({ entries, onEdit, onDelete }) {
  if (!entries || entries.length === 0) {
    return (
      <div className="card empty-state">
        No finance entries found for this filter. Click "Add Entry" to create one.
      </div>
    );
  }

  // Some departments don't use every optional field — hide columns that no
  // entry in the current result set actually has data for, rather than
  // showing a column of dashes.
  const showClientName = entries.some((e) => e.client_name);
  const showPatientName = entries.some((e) => e.patient_name);
  const showPatientPlace = entries.some((e) => e.patient_place);
  const showGeneratedBy = entries.some((e) => e.generated_by);
  const showRevenueType = entries.some((e) => e.revenue_type);

  return (
    <div className="card table-wrap">
      <table className="data-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Category</th>
            {showClientName && <th>Client Name</th>}
            {showPatientName && <th>Patient Name</th>}
            {showPatientPlace && <th>Patient Place</th>}
            {showGeneratedBy && <th>Generated By</th>}
            {showRevenueType && <th>Revenue Type</th>}
            <th className="text-right">Amount</th>
            <th>Remarks</th>
            <th className="text-right">Actions</th>
          </tr>
        </thead>
        <tbody>
          {entries.map((entry) => (
            <tr key={entry.id}>
              <td style={{ whiteSpace: "nowrap" }}>{entry.entry_date}</td>
              <td>
                <span className={`badge ${entry.entry_type === "Income" ? "badge-income" : "badge-expense"}`}>
                  {entry.entry_type}
                </span>
              </td>
              <td>{entry.category}</td>
              {showClientName && <td>{entry.client_name || "—"}</td>}
              {showPatientName && <td>{entry.patient_name || "—"}</td>}
              {showPatientPlace && <td>{entry.patient_place || "—"}</td>}
              {showGeneratedBy && <td>{entry.generated_by || "—"}</td>}
              {showRevenueType && <td>{entry.revenue_type || "—"}</td>}
              <td className="text-right" style={{ fontWeight: 600 }}>{formatCurrency(entry.amount)}</td>
              <td className="truncate">{entry.remarks || "—"}</td>
              <td>
                <div className="actions-cell">
                  <button onClick={() => onEdit(entry)} className="btn-icon" title="Edit">
                    <Pencil size={15} />
                  </button>
                  <button onClick={() => onDelete(entry)} className="btn-icon btn-icon--danger" title="Delete">
                    <Trash2 size={15} />
                  </button>
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}