import React from "react";
import { Pencil, Trash2, FileText } from "lucide-react";
import api from "../api/axios.js";

const formatCurrency = (value) => {
  const number = Number(value || 0);
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(number);
};

const apiOrigin = (api.defaults.baseURL || "")
  .replace(/\/api\/?$/, "")
  .replace(/\/$/, "");

const invoiceHref = (entry) => {
  if (!entry?.invoice_url) return null;
  if (entry.invoice_url.startsWith("http://") || entry.invoice_url.startsWith("https://")) {
    return entry.invoice_url;
  }
  return `${apiOrigin}${entry.invoice_url}`;
};

export default function FinanceTable({
  entries = [],
  onEdit,
  onDelete,
}) {
  if (!entries || entries.length === 0) {
    return (
      <div className="empty-state">
        No finance entries found for this filter. Click "Add Entry" to create one.
      </div>
    );
  }

  const showClientName = entries.some((entry) => entry?.client_name);
  const showGstNumber = entries.some((entry) => entry?.gst_number);
  const showItems = entries.some((entry) => Array.isArray(entry?.items) && entry.items.length > 0);
  const showPatientName = entries.some((entry) => entry?.patient_name);
  const showPatientPlace = entries.some((entry) => entry?.patient_place);
  const showGeneratedBy = entries.some((entry) => entry?.generated_by);
  const showRevenueType = entries.some((entry) => entry?.revenue_type);
  const showInvoice = entries.some((entry) => entry?.invoice_url);

  // Sub-category (AFU)
  const showSubCategory = entries.some((entry) => entry?.sub_category);

  // Executive compensation fields
  const showExecDepartment = entries.some((entry) => entry?.exec_department);
  const showEmployeeName = entries.some((entry) => entry?.employee_name);
  const showSalaryAmount = entries.some((entry) => entry?.salary_amount !== null && entry?.salary_amount !== undefined);
  const showAllowanceAmount = entries.some((entry) => entry?.allowance_amount !== null && entry?.allowance_amount !== undefined);

  return (
    <div className="table-responsive">
      <table className="finance-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Category</th>
            {showSubCategory && <th>Sub-Category</th>}
            {showClientName && <th>Client Name</th>}
            {showGstNumber && <th>GST Number</th>}
            {showItems && <th>Items</th>}
            {showPatientName && <th>Patient Name</th>}
            {showPatientPlace && <th>Patient Place</th>}
            {showGeneratedBy && <th>Generated By</th>}
            {showRevenueType && <th>Revenue Type</th>}
            {showExecDepartment && <th>Exec Dept</th>}
            {showEmployeeName && <th>Employee</th>}
            {showSalaryAmount && <th className="text-right">Salary</th>}
            {showAllowanceAmount && <th className="text-right">Allowance</th>}
            <th className="text-right">Amount</th>
            <th>Remarks</th>
            {showInvoice && <th>Invoice</th>}
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          {entries.map((entry) => {
            const items = Array.isArray(entry.items) ? entry.items : [];
            const itemNames = items
              .map((item) => {
                const qty = Number(item.quantity || 0);
                return `${item.item_name || "Item"} (x${qty})`;
              })
              .join(", ");

            const invoiceUrl = invoiceHref(entry);

            return (
              <tr key={entry.id}>
                <td style={{ whiteSpace: "nowrap" }}>{entry.entry_date || "—"}</td>
                <td>
                  <span className={`badge ${entry.entry_type === "Income" ? "badge-income" : "badge-expense"}`}>
                    {entry.entry_type || "—"}
                  </span>
                </td>
                <td>{entry.category || "—"}</td>
                {showSubCategory && <td>{entry.sub_category || "—"}</td>}
                {showClientName && <td>{entry.client_name || "—"}</td>}
                {showGstNumber && <td>{entry.gst_number || "—"}</td>}
                {showItems && <td>{items.length > 0 ? `${items.length} item${items.length > 1 ? "s" : ""} — ${itemNames}` : "—"}</td>}
                {showPatientName && <td>{entry.patient_name || "—"}</td>}
                {showPatientPlace && <td>{entry.patient_place || "—"}</td>}
                {showGeneratedBy && <td>{entry.generated_by || "—"}</td>}
                {showRevenueType && <td>{entry.revenue_type || "—"}</td>}
                {showExecDepartment && <td>{entry.exec_department || "—"}</td>}
                {showEmployeeName && <td>{entry.employee_name || "—"}</td>}
                {showSalaryAmount && <td className="text-right">{formatCurrency(entry.salary_amount)}</td>}
                {showAllowanceAmount && <td className="text-right">{formatCurrency(entry.allowance_amount)}</td>}
                <td className="text-right" style={{ fontWeight: 600 }}>
                  {formatCurrency(entry.amount)}
                </td>
                <td>{entry.remarks || "—"}</td>
                {showInvoice && (
                  <td>
                    {invoiceUrl ? (
                      <a href={invoiceUrl} target="_blank" rel="noreferrer" className="btn-icon" title={entry.invoice_original_name || "View invoice"}>
                        <FileText size={15} />
                      </a>
                    ) : (
                      "—"
                    )}
                  </td>
                )}
                <td>
                  <div className="actions-cell">
                    <button type="button" onClick={() => onEdit?.(entry)} className="btn-icon" title="Edit">
                      <Pencil size={15} />
                    </button>
                    <button type="button" onClick={() => onDelete?.(entry)} className="btn-icon btn-icon--danger" title="Delete">
                      <Trash2 size={15} />
                    </button>
                  </div>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}